### ISSUE TITLE
Add imtiaz's Tutorial to description

### ISSUE THREAD

**Issue by WilliamsTravis** [WilliamsTravis/Ubuntu-Practice-Machine#3]
The user guide is somewhat out of date too.

**Comment by irangwala** [comment]
Hi Travis: Here is the link to the Introductory Tutorial in PDF which we can mention somewhere on the new DrIP page: https://drive.google.com/file/d/1TD7o81aYA4LmoMQ0k3Q9SOgPLiQqX30V/view?usp=sharing

I was thinking that we can perhaps create a Resources tab in Header and put links for both the DrIP User Guide and this tutorial there. Thanks!!! 

Here is the Google Doc link if you wish to modify it further: https://docs.google.com/document/d/1rEMxjZN5NmI-DuNGQLFnaKdST4eByiidDSYo1uVnXY8/edit?usp=sharing
